services:
  postgres:
    image: postgres:17-alpine
    container_name: portfolio_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network

volumes:
  postgres_data:

networks:
  portfolio_network:
    driver: bridge
