services:
  postgres:
    image: postgres:17-alpine
    container_name: portfolio_postgres
    ports:
      - "${DB_PORT:-5433}:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: portfolio_keycloak
    ports:
      - "${KEYCLOAK_PORT:-8081}:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    volumes:
      - ./config/keycloak/data:/opt/keycloak/data/h2
    networks:
      - portfolio_network

volumes:
  postgres_data:

networks:
  portfolio_network:
    driver: bridge
